### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by tomjaguarpaw**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
This one has a mistake.  I will fix it.

**Comment by boris-marinov** [comment]
Wow, that is awesome, thanks very much.

The article was aimed at beginners, seeing it sparks some interests in seasoned FP developers is super!

Please, feel free to also submit ideas about functional recipes.

**Comment by tomjaguarpaw** [comment]
Careful!  There was a mistake here https://github.com/boris-marinov/boris-marinov.github.io/pull/1/files#diff-c499d9b16e8f148c7f2450b480ab9daeR1 which is why I closed the PR.  The other PR I submitted was correct.

**Comment by tomjaguarpaw** [comment]
Oh, it looks like I didn't even submit the other PR.

**Comment by boris-marinov** [comment]
It's OK, I will remove the i.

**Pull request merged**
